### PR TITLE
chore: highlight command print outs

### PR DESCRIPTION
**Pull request by Jakub-Vacek**
## Description
Solves: https://github.com/superfaceai/cli/issues/345

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have updated the documentation accordingly. For updating Oclif commands documentation use [oclif-dev](https://github.com/oclif/dev-cli#oclif-dev-readme).
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I haven't repeated the code. (DRY)
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by kysely — COMMENTED** [review]
Do you please have screens of this change? I'm not sure whether it shouldn't be solved more systematically

**Comment by julpat** [comment]
I would like to take a look on this as well. E.g. the `underline` can evoke a clickable text.
We will have a discussion with Z and Martyn tomorrow so maybe even more feedback can be done here and probably I will have some spare time to take over and finish it if you are fine with that.

**Comment by Jakub-Vacek** [comment]
Snímek obrazovky 2023-08-03 v 7 00 42

This is how it looks like for `prepare`

@julpat If you have time and ideas how to make this better you can take over this PR (or open new with more general changes)

**Comment by julpat** [comment]
Finally got to this (and have the repository running & explored, so next pair of hands for this kind of stuff).

- Removed the underline to avoid confusion
- Added missing command highlighting
- Point out more at the `execute` command

For the purpose of this PR (and the issue), it seems sufficient to me.
There will be more changes (copy / ux) in the near future, so let's not block this one.

image
image
image

**Comment by Jakub-Vacek** [comment]
Looks OK, what do you think @kysely ?

**Comment by kysely** [comment]
I think it's still verbose but I'm fine either way :)

**Pull request merged**
