### PR TITLE
Feat/format map

### PR DESCRIPTION
**Pull request by Jakub-Vacek**
## Description
This PR adds use of prettier to format generated map. PR also updates application code formatting to match default prettier config.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have updated the documentation accordingly. For updating Oclif commands documentation use [oclif-dev](https://github.com/oclif/dev-cli#oclif-dev-readme).
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I haven't repeated the code. (DRY)
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by kysely — CHANGES_REQUESTED** [review]
Looks good, but definitely belongs to engine :)

**Comment by Jakub-Vacek** [comment]
Ok, I will move map formatting.

**Comment by Jakub-Vacek** [comment]
Moved to engine: https://github.com/superfaceai/edgar-engine/pull/318
I would still like to merge formatting of application code.

**Review by kysely — APPROVED** [review]
Don't know why it's important, but looks fine 👍

**Pull request merged**
